### ISSUE TITLE
brackets swapped arg-st.tex

### ISSUE THREAD

**Issue by stefan11** [langsci/259#116]
![grafik](https://user-images.githubusercontent.com/4655859/111038424-140f3a80-8429-11eb-8edc-3766cfaa35bf.png)

```latex
\avm{
	[arg-st & <\ldots, [head   & verb \\
			    arg-st & \1 > ] \shuffle \1 ]
}
```

Doesn't necessarily need fixing. I just thought I mention it. The ] and > should have been reversed. Interesting that the style does not notice a missing bracket.

**Comment by kopeckyf** [comment]
- `langsci-avm` does not notice a missing bracket because there are no missing brackets: The bracket groups in this example are balanced.
 -  The brackets are swapped as per user input, not anything that happens in `langsci-avm`.
 - `langsci-avm`'s documentation specifically mentions that this is possible, but discourages the user from doing so since it may become unavailable in a future version.
