### ISSUE TITLE
distance too narrow between lines in avms relative-clauses.tex

### ISSUE THREAD

**Issue by stefan11** [langsci/259#78]
![grafik](https://user-images.githubusercontent.com/4655859/106956110-6a0c0680-6736-11eb-9b88-166ec052837b.png)

```latex
\avm{
	[\type*{scope-obj}
	index & \1 \\
	restr &	\{
			[\type*{fact}
			prop|soa  &	[\type*{soa}
						nuc &	[\type*{person}
								instance & \1 ] ] ], \\
            [\type*{fact}
            prop|soa &	[\type*{soa}
            			nuc &	[\type*{speak\_to}
            					speaker & Kim\\
            					addressee & \1 ] ] ]
      		\} 
	] 
}
```

**Comment by kopeckyf** [comment]
Interesting, this is because of the comma, but of course the comma needs to be present in sets to delineate elements. 

Possible solution (note to myself): Install a list of characters that automatically increase the line skip when they are the last character in the line.

Direct solution: Replace `, \\` with `, \smallskip\\`

**Comment by stefan11** [comment]
OK. Thanks!

I am just collecting stuff. To talk about. Don't get stressed by this. =:-) There will probably be tons and tons of duplicate submissions. I just want to make sure that I don't miss anything.

I do not want to patch things up. I collect things I notice and then we maybe can find a solution to all of those in one go and come up with a really, really cool avm package. (a compared to "really cool" =:-)

**Comment by stefan11** [comment]
I added the smallskip and a comment in the tex file %avm todo.
